/* Generated By:JavaCC: Do not edit this line. MiniJajaVisitor.java Version 5.0 */
package fr.univfcomte.comp4.analyseur;

public interface MiniJajaVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTclasse node, Object data);
  public Object visit(ASTident node, Object data);
  public Object visit(ASTdecls node, Object data);
  public Object visit(ASTvnil node, Object data);
  public Object visit(ASTmethode node, Object data);
  public Object visit(ASTtableau node, Object data);
  public Object visit(ASTvar node, Object data);
  public Object visit(ASTcst node, Object data);
  public Object visit(ASTvars node, Object data);
  public Object visit(ASTomega node, Object data);
  public Object visit(ASTmain node, Object data);
  public Object visit(ASTentetes node, Object data);
  public Object visit(ASTenil node, Object data);
  public Object visit(ASTentete node, Object data);
  public Object visit(ASTinstrs node, Object data);
  public Object visit(ASTinil node, Object data);
  public Object visit(ASTtab node, Object data);
  public Object visit(ASTaffectation node, Object data);
  public Object visit(ASTsomme node, Object data);
  public Object visit(ASTincrement node, Object data);
  public Object visit(ASTappelI node, Object data);
  public Object visit(ASTretour node, Object data);
  public Object visit(ASTsi node, Object data);
  public Object visit(ASTtantque node, Object data);
  public Object visit(ASTlistexp node, Object data);
  public Object visit(ASTexnil node, Object data);
  public Object visit(ASTnot node, Object data);
  public Object visit(ASTet node, Object data);
  public Object visit(ASTou node, Object data);
  public Object visit(ASTegal node, Object data);
  public Object visit(ASTsupga node, Object data);
  public Object visit(ASTmoinsU node, Object data);
  public Object visit(ASTplus node, Object data);
  public Object visit(ASTmoinsB node, Object data);
  public Object visit(ASTmult node, Object data);
  public Object visit(ASTdiv node, Object data);
  public Object visit(ASTvrai node, Object data);
  public Object visit(ASTfaux node, Object data);
  public Object visit(ASTappelE node, Object data);
  public Object visit(ASTnbre node, Object data);
  public Object visit(ASTrien node, Object data);
  public Object visit(ASTentier node, Object data);
  public Object visit(ASTbooleen node, Object data);
}
/* JavaCC - OriginalChecksum=53260d20b53920897d63f2ab98d66cd1 (do not edit this line) */
