/* Generated By:JavaCC: Do not edit this line. MiniJajaTreeConstants.java Version 5.0 */
package fr.univfcomte.comp4.analyseur;

public interface MiniJajaTreeConstants
{
  public int JJTCLASSE = 0;
  public int JJTIDENT = 1;
  public int JJTDECLS = 2;
  public int JJTVNIL = 3;
  public int JJTDECL = 4;
  public int JJTVARS = 5;
  public int JJTVAR = 6;
  public int JJTVEXP = 7;
  public int JJTOMEGA = 8;
  public int JJTMETHODE = 9;
  public int JJTMAIN = 10;
  public int JJTENTETES = 11;
  public int JJTENIL = 12;
  public int JJTENTETE = 13;
  public int JJTINSTRS = 14;
  public int JJTINIL = 15;
  public int JJTINSTR = 16;
  public int JJTLISTEXP = 17;
  public int JJTEXNIL = 18;
  public int JJTEXP = 19;
  public int JJTEXP1 = 20;
  public int JJTEXP2 = 21;
  public int JJTEXP3 = 22;
  public int JJTEXP4 = 23;
  public int JJTEXP5 = 24;
  public int JJTTERME = 25;
  public int JJTTERME1 = 26;
  public int JJTFACT = 27;
  public int JJTIDENT1 = 28;
  public int JJTTYPEMETH = 29;
  public int JJTRIEN = 30;
  public int JJTTYPE = 31;
  public int JJTENTIER = 32;
  public int JJTBOOLEEN = 33;


  public String[] jjtNodeName = {
    "classe",
    "ident",
    "decls",
    "vnil",
    "decl",
    "vars",
    "var",
    "vexp",
    "omega",
    "methode",
    "main",
    "entetes",
    "enil",
    "entete",
    "instrs",
    "inil",
    "instr",
    "listexp",
    "exnil",
    "exp",
    "exp1",
    "exp2",
    "exp3",
    "exp4",
    "exp5",
    "terme",
    "terme1",
    "fact",
    "ident1",
    "typemeth",
    "rien",
    "type",
    "entier",
    "booleen",
  };
}
/* JavaCC - OriginalChecksum=cf0ec5002589b64e81901ef47c0b68ae (do not edit this line) */
