/* Generated By:JavaCC: Do not edit this line. MiniJajaDefaultVisitor.java Version 6.0_1 */
package fr.univfcomte.comp4.analyseur;

public class MiniJajaDefaultVisitor implements MiniJajaVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=d23c23e5a6919e0aada6ce60ff685140 (do not edit this line) */
