/* Generated By:JavaCC: Do not edit this line. MiniJajaVisitor.java Version 5.0 */
package fr.univfcomte.comp4.analyseur;

public interface MiniJajaVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=2ec69fe60d931834031093bc4fa08be0 (do not edit this line) */
