/* Generated By:JavaCC: Do not edit this line. JajaCodeTreeConstants.java Version 5.0 */
package fr.univfcomte.comp4.analyseur_JajaCode;

public interface JajaCodeTreeConstants
{
  public int JJTJAJACODE = 0;
  public int JJTJCNIL = 1;
  public int JJTIDENT = 2;
  public int JJTTYPE = 3;
  public int JJTOBJET = 4;
  public int JJTADRESSE = 5;
  public int JJTVOID = 6;
  public int JJTINIT = 7;
  public int JJTSWAP = 8;
  public int JJTNEWVAL = 9;
  public int JJTNEWARRAY = 10;
  public int JJTINVOKE = 11;
  public int JJTRETOUR = 12;
  public int JJTPUSH = 13;
  public int JJTPOP = 14;
  public int JJTLOAD = 15;
  public int JJTALOAD = 16;
  public int JJTSTORE = 17;
  public int JJTASTORE = 18;
  public int JJTSI = 19;
  public int JJTALLERA = 20;
  public int JJTINC = 21;
  public int JJTAINC = 22;
  public int JJTNOP = 23;
  public int JJTJCSTOP = 24;
  public int JJTOMEGA = 25;
  public int JJTVRAI = 26;
  public int JJTFAUX = 27;
  public int JJTNEG = 28;
  public int JJTNOT = 29;
  public int JJTADD = 30;
  public int JJTSUB = 31;
  public int JJTMUL = 32;
  public int JJTDIV = 33;
  public int JJTCMP = 34;
  public int JJTSUP = 35;
  public int JJTOR = 36;
  public int JJTAND = 37;
  public int JJTNBRE = 38;


  public String[] jjtNodeName = {
    "JajaCode",
    "jcnil",
    "ident",
    "type",
    "objet",
    "adresse",
    "void",
    "init",
    "swap",
    "newVal",
    "newarray",
    "invoke",
    "retour",
    "push",
    "pop",
    "load",
    "aload",
    "store",
    "astore",
    "si",
    "allerA",
    "inc",
    "ainc",
    "nop",
    "jcstop",
    "omega",
    "vrai",
    "faux",
    "neg",
    "not",
    "add",
    "sub",
    "mul",
    "div",
    "cmp",
    "sup",
    "or",
    "and",
    "nbre",
  };
}
/* JavaCC - OriginalChecksum=2d2c79465bdcc6f8cdf9c04887163f98 (do not edit this line) */
