/* Generated By:JJTree&JavaCC: Do not edit this line. MiniJajaConstants.java */
package fr.univfcomte.comp4.analyseur;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJajaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAROUV = 7;
  /** RegularExpression Id. */
  int PARFER = 8;
  /** RegularExpression Id. */
  int ACCOUV = 9;
  /** RegularExpression Id. */
  int ACCFER = 10;
  /** RegularExpression Id. */
  int CROOUV = 11;
  /** RegularExpression Id. */
  int CROFER = 12;
  /** RegularExpression Id. */
  int PVIRG = 13;
  /** RegularExpression Id. */
  int VIRG = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int MAIN = 20;
  /** RegularExpression Id. */
  int FINAL = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MOINS = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int SUPGA = 28;
  /** RegularExpression Id. */
  int EGAL = 29;
  /** RegularExpression Id. */
  int ET = 30;
  /** RegularExpression Id. */
  int OU = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int AFFECT = 33;
  /** RegularExpression Id. */
  int AFFECTPLUS = 34;
  /** RegularExpression Id. */
  int INCR = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int BOOLEAN = 37;
  /** RegularExpression Id. */
  int VOID = 38;
  /** RegularExpression Id. */
  int IDENT = 39;
  /** RegularExpression Id. */
  int NOMBRE = 40;
  /** RegularExpression Id. */
  int LETTRE = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"class\"",
    "\"false\"",
    "\"true\"",
    "\"if\"",
    "\"else\"",
    "\"main\"",
    "\"final\"",
    "\"return\"",
    "\"while\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"=\"",
    "\"+=\"",
    "\"++\"",
    "\"int\"",
    "\"boolean\"",
    "\"void\"",
    "<IDENT>",
    "<NOMBRE>",
    "<LETTRE>",
  };

}
